name: diceware-rs
version: 0.1.0
author: Joshua Shope <haxrhax@gmail.com>
about: Generate diceware passwords from the command line, fast and without hassle
args:
  - AMOUNT:
      help: Sets the number of passphrases generated (Defaults to 1) 
      default_value: "1"
      index: 1
  - length:
      help: The amount of unique words in the passphrase
      long: len
      value_name: NUMBER
      takes_value: true
      default_value: "3"
  

